[[redirects]]
  from = "/robots.txt"
  to = "/robots.txt"
  status = 200
  force = true

[[redirects]]
  from = "/prod"
  to = "/prod.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 200